services:
  database:
    build: ./database
    ports: 
      - "5432:5432" 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - backend
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - pg_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL} 
      SUPBASE_JWT_URL: ${SUPBASE_JWT_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      BACKEND_BASE_URL: http://backend:5000/api/v1
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    command: npm run dev
    networks:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  backend:
    driver: bridge
  pg_network:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data: